# Generated by Django 4.0 on 2022-01-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('wifi', models.CharField(max_length=3)),
                ('toilet', models.CharField(max_length=3)),
                ('smokingarea', models.CharField(max_length=3)),
                ('ac_room', models.CharField(max_length=3)),
                ('avg_price', models.IntegerField()),
            ],
        ),
    ]
